import fireElemental from "../../assets/elemental-fire.png";
import waterElemental from "../../assets/elemental-water.png";
import airElemental from "../../assets/elemental-air.png";
import earthElemental from "../../assets/earth-elemental.png";
import { ElementalType } from "../types/ElementalType";

export const Elementals: ElementalType[] = [
  {
    duration: 46,
    roundTrigger: false,
    name: "Fire elemental",
    img: fireElemental,
    greater: {
      size: "huge(extraplanar)",
      HD: "21d8+84(178 hp)",
      initiative: "+12",
      speed: "60ft",
      AC: "24 , touch 16, flat-footed 16",
      babGrapple: "+15/+28",
      attack: "Slam +22 melee (2d8+5 plus 2d8 fire)",
      fullAttack: "2 slams +22 melee(2d8+5 plus 2d8 fire)",
      spaceReach: "15ft / 15ft",
      specialAttacks: "burn",
      specialQualities:
        "Damage reduction 10, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold",
      saves: "Fort +11, Ref +20, Will +9",
      abilities: "Str 20, Dex 27, Con 18, Int 6, Wis 11, Cha 11",
      skills: "Listen +14, Spot +14",
      feats:
        "Alertness, Blind Fight, Combat Reflexes, Dodge, Improved Initiative B, Iron Will, Mobility, Spring Attack, Weapon FinesseB, Weapon Focus (slam)",
      aligment: "Usually neutral",
      burnDc: "Burn save DC 24",
    },
    huge: {
      size: "huge(extraplanar)",
      HD: "16d8+64(136 hp)",
      initiative: "+11",
      speed: "60ft",
      AC: "19 , touch 15, flat-footed 12",
      babGrapple: "+12/+24",
      attack: "Slam +17 melee (2d8+4 plus 2d8 fire)",
      fullAttack: "2 slams +17 melee(2d8+4 plus 2d8 fire)",
      spaceReach: "15ft / 15ft",
      specialAttacks: "burn",
      specialQualities:
        "Damage reduction 5, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold",
      saves: "Fort +9, Ref +17, Will +7",
      abilities: "Str 18, Dex 25, Con 18, Int 6, Wis 11, Cha 11",
      skills: "Listen +11, Spot +12",
      feats:
        "Alertness, Combat Reflexes, Dodge, Improved Initiative B, Iron Will, Mobility, Spring Attack, Weapon FinesseB",
      aligment: "Usually neutral",
      burnDc: "Burn save DC 22",
    },
    large: {
      size: "large(extraplanar)",
      HD: "8d8+24 (60 hp)",
      initiative: "+9",
      speed: "50ft",
      AC: "18, touch 14, flat-footed 13",
      babGrapple: "+6/+12",
      attack: "Slam +10 melee (2d6+2 plus 2d6 fire)",
      fullAttack: "2 slams +10 melee (2d6+2 plus 2d6 fire)",
      spaceReach: "10 ft./10 ft.",
      specialAttacks: "burn",
      specialQualities:
        "Damage reduction 5, darkvision 60 ft., elemental traits, immunity to fire, vulnerability to cold",
      saves: "Fort +5, Ref +11, Will +2",
      abilities: "Str 14, Dex 21, Con 16, Int 6, Wis 11, Cha 11",
      skills: "Listen +5, Spot +6",
      feats:
        "Dodge, Improved Initiative B, Mobility, Spring Attack, Weapon FinesseB",
      aligment: "Usually neutral",
      burnDc: "Burn save DC 17",
    },
  },
  {
    duration: 46,
    roundTrigger: false,
    name: "Earth elemental",
    img: earthElemental,
    greater: {
      size: "huge(extraplanar)",
      HD: "21d8+105 (199 hp)",
      initiative: "-1",
      speed: "30 ft",
      AC: "20, touch 7, flat-footed 20",
      babGrapple: "	+15/+33",
      attack: "Slam +23 melee (2d10+10)",
      fullAttack: "2 slams +23 melee (2d10+10)",
      spaceReach: "15ft / 15ft",
      specialAttacks: "Earth mastery, push",
      specialQualities:
        "Damage reduction 10, earth glide, darkvision 60 ft., elemental traits",
      saves: "Fort +17, Ref +6, Will +9",
      abilities: "Str 31, Dex 8, Con 21, Int 8, Wis 11, Cha 11",
      skills: "Listen +14, Spot +14",
      feats:
        "Alertness, Awesome Blow, Cleave, Great Cleave, Improved Bull Rush, Improved Sunder, Iron Will, Power Attack",
      aligment: "Usually neutral",
    },
    huge: {
      size: "16d8+80 (152 hp)",
      HD: "16d8+80 (152 hp)",
      initiative: "-1",
      speed: "30 ft",
      AC: "18, touch 7, flat-footed 18",
      babGrapple: "+12/+29",
      attack: "Slam +19 melee (2d10+9)",
      fullAttack: "2 slams +19 melee (2d10+9)",
      spaceReach: "15ft / 15ft",
      specialAttacks: "Water mastery, drench, vortex",
      specialQualities:
        "Damage reduction 5/-, earth glide, darkvision 60 ft., elemental traits",
      saves: "Fort +15, Ref +4, Will +7",
      abilities: "	Str 29, Dex 8, Con 21, Int 6, Wis 11, Cha 11",
      skills: "Listen +10, Spot +9",
      feats:
        "Awesome Blow, Cleave, Great Cleave, Improved Bull Rush, Iron Will, Power Attack",
      aligment: "Usually neutral",
    },
    large: {
      size: "large(extraplanar)",
      HD: "8d8+32 (68 hp)",
      initiative: "-1",
      speed: "20 ft.",
      AC: "18, touch 8, flat-footed 18",
      babGrapple: "+6/+17",
      attack: "Slam +12 melee (2d8+7)",
      fullAttack: "2 slams +12 melee (2d8+7)",
      spaceReach: "10 ft./10 ft.",
      specialAttacks: "	Earth mastery, push",
      specialQualities:
        "Damage reduction 5, earth glide, darkvision 60 ft., elemental traits",
      saves: "Fort +10, Ref +1, Will +2",
      abilities: "Str 25, Dex 8, Con 19, Int 6, Wis 11, Cha 11",
      skills: "Listen +6, Spot +5",
      feats: "Cleave, Great Cleave, Power Attack",
      aligment: "Usually neutral",
    },
  },
  {
    duration: 46,
    roundTrigger: false,
    name: "Water elemental",
    img: waterElemental,
    greater: {
      size: "huge(extraplanar)",
      HD: "21d8+105 (199 hp)",
      initiative: "+5",
      speed: "30 ft, swim 120 ft",
      AC: "22, touch 13, flat-footed 17",
      babGrapple: "+15/+31",
      attack: "Slam +21 melee (2d10+8)",
      fullAttack: "2 slams +21 melee (2d10+8)",
      spaceReach: "15ft / 15ft",
      specialAttacks: "Water mastery, drench, vortex",
      specialQualities:
        "Damage reduction 10/-, darkvision 60 ft., elemental traits",
      saves: "Fort +17, Ref +14, Will +9",
      abilities: "Str 26, Dex 20, Con 21, Int 8, Wis 11, Cha 11",
      skills: "Listen +14, Spot +14",
      feats:
        "Alertness, Cleave, Great Cleave, Improved Bull Rush, Improved Sunder, Iron Will, Lightning Reflexes, Power Attack",
      aligment: "Usually neutral",
    },
    huge: {
      size: "huge(extraplanar)",
      HD: "16d8+80 (152 hp)",
      initiative: "+4",
      speed: "30 ft, swim 120 ft",
      AC: "21 , touch 12, flat-footed 17",
      babGrapple: "+12/+27",
      attack: "Slam +17 melee (2d10+7)",
      fullAttack: "2 slams +17 melee (2d10+7)",
      spaceReach: "15ft / 15ft",
      specialAttacks: "Water mastery, drench, vortex",
      specialQualities:
        "Damage reduction 5/-, darkvision 60 ft., elemental traits",
      saves: "Fort +15, Ref +9, Will +7",
      abilities: "Str 24, Dex 18, Con 21, Int 6, Wis 11, Cha 11",
      skills: "	Listen +11, Spot +12",
      feats:
        "Alertness, Cleave, Great Cleave, Power Attack, Improved Bull Rush, Iron Will",
      aligment: "Usually neutral",
    },
    large: {
      size: "large(extraplanar)",
      HD: "8d8+32 (68 hp)",
      initiative: "+2",
      speed: "20 ft. , swim 90 ft.",
      AC: "20, touch 11, flat-footed 18",
      babGrapple: "+6/+15",
      attack: "Slam +10 melee (2d8+5)",
      fullAttack: "	2 slams +10 melee (2d8+5)",
      spaceReach: "10 ft./10 ft.",
      specialAttacks: "Water mastery, drench, vortex",
      specialQualities:
        "Damage reduction 5/-, darkvision 60 ft., elemental traits",
      saves: "Fort +10, Ref +4, Will +2",
      abilities: "Str 20, Dex 14, Con 19, Int 6, Wis 11, Cha 11",
      skills: "Listen +5, Spot +6",
      feats: "Cleave, Great Cleave, Power Attack",
      aligment: "Usually neutral",
    },
  },
  {
    duration: 46,
    roundTrigger: false,
    name: "Air Elemental, Greater",
    img: airElemental,
    greater: {
      size: "Huge",
      HD: "21d8+84 (178 hp)",
      initiative: "+14",
      speed: "Fly 100 ft. (perfect) (20 squares)",
      AC: "26 (–2 size, +10 Dex, +8 natural), touch 18, flat-footed 16",
      babGrapple: "+15/+28",
      attack: "Slam +23 melee (2d8+5)",
      fullAttack: "2 slams +23 melee (2d8+5)",
      spaceReach: "15 ft./15 ft.",
      specialAttacks: "Air mastery, whirlwind",
      specialQualities:
        "Damage reduction 10/–, darkvision 60 ft., elemental traits",
      saves: "Fort +11, Ref +22, Will +9",
      abilities: "Str 20, Dex 31, Con 18, Int 8, Wis 11, Cha 11",
      skills: "Listen +14, Spot +14",
      feats:
        "Alertness, Blind-Fight, Combat Reflexes, Flyby Attack, Improved Initiative B, Iron Will, Mobility, Power Attack, Spring Attack, Weapon FinesseB",
      aligment: "Usually neutral",
    },
    huge: {
      size: "Huge",
      HD: "16d8+64 (136 hp)",
      initiative: "+13",
      speed: "Fly 100 ft. (perfect) (20 squares)",
      AC: "21 (–2 size, +9 Dex, +4 natural), touch 17, flat-footed 12",
      babGrapple: "+12/+24",
      attack: "Slam +19 melee (2d8+4)",
      fullAttack: "2 slams +19 melee (2d8+4)",
      spaceReach: "15 ft./15 ft.",
      specialAttacks: "Air mastery, whirlwind",
      specialQualities:
        "Damage reduction 5/–, darkvision 60 ft., elemental traits",
      saves: "Fort +9, Ref +19, Will +5",
      abilities: "Str 18, Dex 29, Con 18, Int 6, Wis 11, Cha 11",
      skills: "Listen +11, Spot +12",
      feats:
        "Alertness, Combat Reflexes, Dodge, Flyby Attack, Improved Initiative B, Mobility, Spring Attack, Weapon FinesseB",
      aligment: "Usually neutral",
    },
    large: {
      size: "Large",
      HD: "8d8+24 (60 hp)",
      initiative: "+11",
      speed: "Fly 100 ft. (perfect) (20 squares)",
      AC: "20 (–1 size, +7 Dex, +4 natural), touch 16, flat-footed 13",
      babGrapple: "+6/+12",
      attack: "Slam +12 melee (2d6+2)",
      fullAttack: "2 slams +12 melee (2d6+2)",
      spaceReach: "10 ft./10 ft.",
      specialAttacks: "Air mastery, whirlwind",
      specialQualities:
        "Damage reduction 5/–, darkvision 60 ft., elemental traits",
      saves: "Fort +5, Ref +13, Will +2",
      abilities: "Str 14, Dex 25, Con 16, Int 6, Wis 11, Cha 11",
      skills: "Listen +5, Spot +6",
      feats:
        "Combat Reflexes, Dodge, Flyby Attack, Improved InitiativeB, Weapon FinesseB",
      aligment: "Usually neutral",
    },
  },
];
