export interface ElementalType {
  handleSummon: () => void;
  duration: number;
  roundTrigger: boolean;
  name: string;
  img: string;
  greater: {
    size: string;
    HD: string;
    initiative: string;
    speed: string;
    AC: string;
    babGrapple: string;
    attack: string;
    fullAttack: string;
    spaceReach: string;
    specialAttacks: string;
    specialQualities: string;
    saves: string;
    abilities: string;
    skills: string;
    feats: string;
    aligment: string;
    burnDc?: string;
  };
  huge: {
    size: string;
    HD: string;
    initiative: string;
    speed: string;
    AC: string;
    babGrapple: string;
    attack: string;
    fullAttack: string;
    spaceReach: string;
    specialAttacks: string;
    specialQualities: string;
    saves: string;
    abilities: string;
    skills: string;
    feats: string;
    aligment: string;
    burnDc?: string;
  };
  large: {
    size: string;
    HD: string;
    initiative: string;
    speed: string;
    AC: string;
    babGrapple: string;
    attack: string;
    fullAttack: string;
    spaceReach: string;
    specialAttacks: string;
    specialQualities: string;
    saves: string;
    abilities: string;
    skills: string;
    feats: string;
    aligment: string;
    burnDc?: string;
  };
}
